{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.serviceBack.name }}
  name: {{ .Values.serviceBack.name }}
{{- else }}
  name: {{ template "fullname" . }}-backend
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.serviceBack.annotations }}
  annotations:
{{ toYaml .Values.serviceBack.annotations | indent 4 }}
{{- end }}
spec:
  # type: {{ .Values.serviceBack.type }}
  ports:
  - port: {{ .Values.serviceBack.externalPort }}
    targetPort: {{ .Values.serviceBack.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}