{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-backend
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
#         env:
# {{- range $pkey, $pval := .Values.env }}
#         - name: {{ $pkey }}
#           value: {{ quote $pval }}
{{- end }}
        ports:
        - containerPort: {{ .Values.serviceBack.internalPort }}
        # livenessProbe:
        #   httpGet:
        #     path: {{ .Values.probePath }}
        #     port: {{ .Values.serviceBack.internalPort }}
          # initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          # periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          # successThreshold: {{ .Values.livenessProbe.successThreshold }}
          # timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.serviceBack.internalPort }}
          # periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          # successThreshold: {{ .Values.readinessProbe.successThreshold }}
          # timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        command: {{ .Values.serviceBack.command }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end }}
